globalvar playerInventory, playerInventoryWidth;
playerInventoryWidth = 5;
playerInventory = ds_grid_create(playerInventoryWidth, 1);

additem(playerInventory, "Man", 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", candy_01a, "");
additem(playerInventory, "Man1", 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", candy_01a, "");
additem(playerInventory, "Man2", 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", candy_01a, "");
additem(playerInventory, "Man3", 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", candy_01a, "");
additem(playerInventory, "Man4", 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", candy_01a, "");
additem(playerInventory, "Man5", 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", candy_01a, "");
additem(playerInventory, "Man6", 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", candy_01a, "");
additem(playerInventory, "Man7", 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", candy_01a, "");
additem(playerInventory, "Man8", 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", candy_01a, "");
additem(playerInventory, "Man9", 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", candy_01a, "");
additem(playerInventory, "Man10", 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", candy_01a, "");
additem(playerInventory, "Man11", 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", candy_01a, "");
additem(playerInventory, "Man12", 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", candy_01a, "");
additem(playerInventory, "Man13", 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", candy_01a, "");
additem(playerInventory, "Man14", 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", candy_01a, "");
additem(playerInventory, "Man15", 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", candy_01a, "");
additem(playerInventory, "Man16", 1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", candy_01a, "");
